%%
dir_rst = '.\rst';
name_algo = 'AOSOLogitBoost';
name_data = {...
  'optdigits',...
  'pendigits',...
   'zipcode',...
  };

% name_data = {...
%   'optdigits',...
%   'pendigits',...
%    'zipcode',...
%   'letter15k',...
%   'letter',...
%   'letter2K',...
%   'letter4K',...
%   'isolet',...
%   'mnist',...
%   'mnist10k',...
%   'poker25kT1',...
%   'poker25kT2',...
%   'poker100k',...
%   'poker150k',...
%   'poker275k',...
%   'poker525k',...
%   'covertype290k',...
%   'covertype145k'
%   };

%%
hh = rst_checker();
for i = 1 : numel(name_data)
  hh.print2(dir_rst,name_algo, name_data{i});
end
