%%
T10k = 10000;
Tpre = 2000;
dir_data_root = 'D:\Users\sp\data\dataset_mat';
dir_rst_root = 'D:\Users\sp\code_work\tentative\VTLogitBoost\rst_uci\VTLogitBoost';
% cdata = {...
%   { fullfile(dir_data,'mnist10k.mat'),...
%     fullfile(dir_out,'mnist10k'),...
%    T10k*10,Tpre},...
%   { fullfile(dir_data,'M-Basic.mat'),...
%     fullfile(dir_out,'M-Basic'),...
%    T10k*10,Tpre},...   
%   { fullfile(dir_data,'M-Rotate.mat'),...
%     fullfile(dir_out,'M-Rotate'),...
%    T10k*10,Tpre},...     
%   { fullfile(dir_data,'M-Image.mat'),...
%     fullfile(dir_out,'M-Image'),...
%    T10k*10,Tpre},...       
%   { fullfile(dir_data,'M-Rand.mat'),...
%     fullfile(dir_out,'M-Rand'),...
%    T10k*10,Tpre},...       
%   { fullfile(dir_data,'M-Noise1.mat'),...
%     fullfile(dir_out,'M-Noise1'),...
%    T10k*10,Tpre},...
%   { fullfile(dir_data,'M-Noise2.mat'),...
%     fullfile(dir_out,'M-Noise2'),...
%    T10k*10,Tpre},...   
%   { fullfile(dir_data,'M-Noise3.mat'),...
%     fullfile(dir_out,'M-Noise3'),...
%    T10k*10,Tpre},...     
%   { fullfile(dir_data,'M-Noise4.mat'),...
%     fullfile(dir_out,'M-Noise4'),...
%    T10k*10,Tpre},...       
%   { fullfile(dir_data,'M-Noise5.mat'),...
%     fullfile(dir_out,'M-Noise5'),...
%    T10k*10,Tpre},...   
%   { fullfile(dir_data,'M-Noise6.mat'),...
%     fullfile(dir_out,'M-Noise6'),...
%    T10k*10,Tpre},...         
% };
cdata = {...
  { fullfile(dir_data_root,'covertype_kegl.mat'),...
    fullfile(dir_rst_root,'covertype_kegl'),...
   T10k*10,Tpre}  
};
cv = {0.1};
cJ = {70};
cns = {1};
dir_code = 'D:\Users\sp\code_work\tentative\VTLogitBoost\';
%%
jm = findResource('scheduler','type','local');
job = createJob(jm);
set(job,'PathDependencies',{dir_code});

uci_par_VTLogitBoost.create_tasks(job,...
  cdata,cv,cJ,cns)

submit(job);

